# Generated by Django 4.2.19 on 2025-05-31 21:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draf', 'Draf'), ('published', 'Published')], default='draf', max_length=10),
        ),
    ]
