# Generated by Django 4.2.19 on 2025-05-12 17:33

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_package', models.CharField(max_length=255, unique=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('duration', models.PositiveIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
